-- create master table
CREATE TABLE DEV_BRONZE.UTILS.MASTER_RAW_API_DELIVERY (
    RAW_DATA                    VARIANT,
    SOURCE_PATH                 VARCHAR, -- Extracted prefix (e.g., 'api' or 'delivery')
    METADATA_FILE_NAME          VARCHAR,
    METADATA_FILE_ROW_NUMBER    BIGINT,
    METADATA_FILE_CONTENT_KEY   VARCHAR,
    METADATA_FILE_LAST_MODIFIED TIMESTAMP_NTZ,
    METADATA_START_SCAN_TIME    TIMESTAMP_NTZ
);

-- create raw tables
create or replace TABLE DEV_BRONZE.API.RAW_ORDERS_INC (
	RAW_DATA VARIANT,
	METADATA_FILE_NAME VARCHAR(16777216),
	METADATA_FILE_ROW_NUMBER NUMBER(38,0),
	METADATA_FILE_CONTENT_KEY VARCHAR(16777216),
	METADATA_FILE_LAST_MODIFIED TIMESTAMP_NTZ(9),
	METADATA_START_SCAN_TIME TIMESTAMP_LTZ(9),
	INGESTED_AT TIMESTAMP_LTZ(9) DEFAULT CURRENT_TIMESTAMP()
);

create or replace TABLE DEV_BRONZE.API.RAW_ORDERS_HISTORY_INC (
	RAW_DATA VARIANT,
	METADATA_FILE_NAME VARCHAR(16777216),
	METADATA_FILE_ROW_NUMBER NUMBER(38,0),
	METADATA_FILE_CONTENT_KEY VARCHAR(16777216),
	METADATA_FILE_LAST_MODIFIED TIMESTAMP_NTZ(9),
	METADATA_START_SCAN_TIME TIMESTAMP_LTZ(9),
	INGESTED_AT TIMESTAMP_LTZ(9) DEFAULT CURRENT_TIMESTAMP()
);

create or replace TABLE DEV_BRONZE.API.RAW_LANDING_ZONES_INC (
	RAW_DATA VARIANT,
	METADATA_FILE_NAME VARCHAR(16777216),
	METADATA_FILE_ROW_NUMBER NUMBER(38,0),
	METADATA_FILE_CONTENT_KEY VARCHAR(16777216),
	METADATA_FILE_LAST_MODIFIED TIMESTAMP_NTZ(9),
	METADATA_START_SCAN_TIME TIMESTAMP_LTZ(9),
	INGESTED_AT TIMESTAMP_LTZ(9) DEFAULT CURRENT_TIMESTAMP()
);

create or replace TABLE DEV_BRONZE.DELIVERY.RAW_CELL_INC (
	RAW_DATA VARIANT,
	METADATA_FILE_NAME VARCHAR(16777216),
	METADATA_FILE_ROW_NUMBER NUMBER(38,0),
	METADATA_FILE_CONTENT_KEY VARCHAR(16777216),
	METADATA_FILE_LAST_MODIFIED TIMESTAMP_NTZ(9),
	METADATA_START_SCAN_TIME TIMESTAMP_LTZ(9),
	INGESTED_AT TIMESTAMP_LTZ(9) DEFAULT CURRENT_TIMESTAMP()
);

-- create snowpipe which loads data from API and DELIVERY schema both
CREATE OR REPLACE PIPE DEV_BRONZE.UTILS.P_MASTER_RAW_API_DELIVERY
AUTO_INGEST = TRUE 
AWS_SNS_TOPIC = 'arn:aws:sns:eu-west-1:245475270127:manna-dms-snowflake-snowpipe-prod' 
AS
COPY INTO DEV_BRONZE.UTILS.MASTER_RAW_API_DELIVERY (
    RAW_DATA, 
    SOURCE_PATH,
    METADATA_FILE_NAME, 
    METADATA_FILE_ROW_NUMBER, 
    METADATA_FILE_CONTENT_KEY, 
    METADATA_FILE_LAST_MODIFIED, 
    METADATA_START_SCAN_TIME
)
FROM (
  SELECT 
    $1,
    REGEXP_SUBSTR(METADATA$FILENAME, 'cdc/zinc/([^/]+)', 1, 1, 'e'),
    METADATA$FILENAME,       
    METADATA$FILE_ROW_NUMBER,
    METADATA$FILE_CONTENT_KEY,
    METADATA$FILE_LAST_MODIFIED,
    METADATA$START_SCAN_TIME
  FROM @"DEV_BRONZE"."UTILS"."SNOWFLAKE_MANNA_DMS_PROD"/cdc/zinc/
)
FILE_FORMAT = DEV_BRONZE.UTILS.FF_PARQUET_FORMAT
PATTERN = '.*\/[0-9]{4}\/[0-9]{2}\/[0-9]{2}\/.*\.parquet';

-- create stream on top of master raw table

-- manual COPY INTO for initial load files and previous incremental files ingestion

-- stored procedure to route the new incremental files to respective raw tables

-- stored procedure call
CALL DEV_BRONZE.UTILS.P_ROUTE_STREAM_DATA('DEV_BRONZE.UTILS.STR_MASTER_RAW_API_DELIVERY');

-- task that calls ths stored procedure