CREATE OR REPLACE PIPE DEV_BRONZE.DELIVERY.P_RAW_CELL
AUTO_INGEST = TRUE 
AWS_SNS_TOPIC='arn:aws:sns:eu-west-1:245475270127:manna-dms-snowflake-snowpipe-prod' 
AS
COPY INTO DEV_BRONZE.DELIVERY.RAW_CELL (
    RAW_DATA, 
    METADATA_FILE_NAME, 
    METADATA_FILE_ROW_NUMBER, 
    METADATA_FILE_CONTENT_KEY, 
    METADATA_FILE_LAST_MODIFIED, 
    METADATA_START_SCAN_TIME
)
FROM (
  SELECT 
    $1,                      -- The actual Parquet data goes into RAW_DATA
    METADATA$FILENAME,       -- File name
    METADATA$FILE_ROW_NUMBER,-- Row number within the file
    METADATA$FILE_CONTENT_KEY,-- Unique fingerprint of the file
    METADATA$FILE_LAST_MODIFIED,
    METADATA$START_SCAN_TIME
  FROM @"DEV_BRONZE"."UTILS"."SNOWFLAKE_MANNA_DMS_PROD"/cdc/zinc/delivery/cell/
)
FILE_FORMAT = DEV_BRONZE.UTILS.FF_PARQUET_FORMAT;

CREATE OR REPLACE PIPE DEV_BRONZE.API.P_RAW_ORDERS_HISTORY
AUTO_INGEST = TRUE
AWS_SNS_TOPIC='arn:aws:sns:eu-west-1:245475270127:manna-dms-snowflake-snowpipe-prod'
AS
COPY INTO DEV_BRONZE.API.RAW_ORDERS_HISTORY (
    RAW_DATA,
    METADATA_FILE_NAME,
    METADATA_FILE_ROW_NUMBER,
    METADATA_FILE_CONTENT_KEY,
    METADATA_FILE_LAST_MODIFIED,
    METADATA_START_SCAN_TIME
)
FROM (
  SELECT
    $1,                      
    METADATA$FILENAME,       
    METADATA$FILE_ROW_NUMBER,
    METADATA$FILE_CONTENT_KEY,
    METADATA$FILE_LAST_MODIFIED,
    METADATA$START_SCAN_TIME
  FROM @"DEV_BRONZE"."UTILS"."SNOWFLAKE_MANNA_DMS_PROD"/cdc/zinc/api/orders_history/
)
FILE_FORMAT = DEV_BRONZE.UTILS.FF_PARQUET_FORMAT;